name: Publish ./public into gh-pages branch

# Prevent concurrent deployments
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
jobs:
  build-test-publish:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y golang-go netcat-openbsd

      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: hugo-${{ hashFiles('go.sum') }}
          restore-keys: hugo-

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: playwright-

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build
        run: hugo --minify
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production

      - name: Run e2e tests
        run: |
          hugo server -D & # Start Hugo server in background
          while ! nc -z localhost 1313; do
            sleep 0.1
          done
          npx playwright test tests/e2e.spec.js
          pkill hugo    # Stop Hugo server after tests

      - name: Publish to gh-pages branch
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
